import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:http/http.dart' as http;

class PdfService {
  /// Generates and shares a PDF report for a specific scan.
  /// [imageUrl] can be a local path or a network URL.
  Future<void> generateAndShareReport({
    required String imageUrl,
    required String prediction,
    required String confidence,
    required String symptoms,
    required String date,
  }) async {
    final pdf = pw.Document();

    // Load fonts (using standard PDF fonts to keep it simple and fast/compatible)
    // For more complex apps we might load GoogleFonts, but standard is safer for sharing.
    
    // Load image
    Uint8List? imageBytes;
    try {
      if (imageUrl.startsWith('http')) {
        final response = await http.get(Uri.parse(imageUrl));
        if (response.statusCode == 200) {
          imageBytes = response.bodyBytes;
        }
      } else {
        // Local file or asset logic if needed, but for history it's usually URL
      }
    } catch (e) {
      // Handle error or use placeholder
      debugPrint("Error loading image for PDF: $e");
    }

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text("EyeVLM Medical Report", style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.teal)),
                    pw.Text("Date: $date", style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),

              // Image Section
              if (imageBytes != null)
                pw.Container(
                  height: 200,
                  alignment: pw.Alignment.center,
                  child: pw.Image(pw.MemoryImage(imageBytes), fit: pw.BoxFit.contain),
                )
              else
                pw.Container(
                  height: 100,
                  alignment: pw.Alignment.center,
                  child: pw.Text("[Image not available]"),
                ),
              
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 20),

              // Results Section
              pw.Text("Analysis Results", style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              
              _buildInfoRow("Prediction", prediction),
              _buildInfoRow("Confidence", confidence),
              _buildInfoRow("Reported Symptoms", symptoms.isEmpty ? "None" : symptoms),

              pw.SizedBox(height: 40),
              
              // Standard Disclaimer
              pw.Container(
                padding: const pw.EdgeInsets.all(10),
                decoration: pw.BoxDecoration(
                  color: PdfColors.grey100,
                  borderRadius: pw.BorderRadius.circular(8),
                ),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text("DISCLAIMER", style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                    pw.Text(
                      "This report is generated by an AI system (EyeVLM) and acts as an early indication tool only. "
                      "It is NOT a medical diagnosis. Please consult a certified ophthalmologist for professional medical advice.",
                      style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
                    ),
                  ],
                ),
              ),
              
              pw.Spacer(),
              pw.Center(
                child: pw.Text("Generated by EyeVLM App", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
              ),
            ],
          );
        },
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'eye_report_$date.pdf');
  }

  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 5),
      child: pw.Row(
        children: [
          pw.SizedBox(width: 120, child: pw.Text("$label:", style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
          pw.Expanded(child: pw.Text(value)),
        ],
      ),
    );
  }
}
